deals/urls.py
from django.urls import path

from deals import views

urlpatterns = [
    path("list/", views.DealListView.as_view(), name="deal_list"),
    path("create/", views.DealCreateView.as_view(), name="deal_create"),
    path("<uuid:pk>/update/", views.DealUpdateView.as_view(), name="deal_update"),
    path("<uuid:pk>/detail/", views.DealDetailView.as_view(), name="deal_detail"),
    path("<uuid:pk>/delete/", views.DealDeleteView.as_view(), name="deal_delete"),
    path(
        "price/list/", views.ProductPriceListView.as_view(), name="product_price_list"
    ),
]

market/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("allauth.urls")),
    path("invitations/", include("invitations.urls")),
    path("", include("catalogs.urls")),
    path("", include("accounts.urls")),
    path("", include("dashboard.urls")),
    path("support/", include("support.urls")),
    path("deal/", include("deals.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api-token-auth/", obtain_auth_token),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
        path("silk/", include("silk.urls")),
    ] + urlpatterns

support/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from uuid import uuid4

User = get_user_model()


class Ticket(models.Model):
    id = models.UUIDField(
        _("Message ID"), primary_key=True, default=uuid4, unique=True, editable=False
    )
    user = models.ForeignKey(User, verbose_name=_("User"), on_delete=models.CASCADE)
    subject = models.CharField(_("Subject"), max_length=50)
    text = models.TextField(_("Message"))
    image = models.ImageField(_("Image"), upload_to="media/", blank=True, null=True)
    timestamp = models.DateTimeField(_("Timestamp"), auto_now_add=True)

    class Meta:
        ordering = ["-timestamp"]
        verbose_name = _("Ticket")
        verbose_name = _("Tickets")

    def __str__(self) -> str:
        return f"{self.user} {self.subject}"


class Reply(models.Model):
    id = models.UUIDField(
        _("Reply ID"), primary_key=True, default=uuid4, unique=True, editable=False
    )
    user = models.ForeignKey(
        User, verbose_name=_("User"), on_delete=models.CASCADE, blank=True, null=True
    )
    ticket = models.ForeignKey(
        Ticket, verbose_name=_("Ticket"), on_delete=models.CASCADE
    )
    text = models.TextField(_("Message"))
    image = models.ImageField(_("Image"), upload_to="media/", blank=True, null=True)
    timestamp = models.DateTimeField(_("Timestamp"), auto_now_add=True)

    class Meta:
        verbose_name = _("Reply")
        verbose_name_plural = _("Replyes")

    def __str__(self) -> str:
        return f"{self.ticket.user} {self.ticket.subject}"

templates/layouts/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - {{ web_title }}</title>
    <link rel="stylesheet" href="{% static 'assets/css/main/app.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/pages/auth.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/logo/favicon.svg' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'assets/images/logo/favicon.png' %}" type="image/png">
</head>

<body>
    <div id="auth">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

templates/layouts/error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - {{ web_title }}</title>
    <link rel="stylesheet" href="{% static 'assets/css/main/app.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/pages/error.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/logo/favicon.svg' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'assets/images/logo/favicon.png' %}" type="image/png">
</head>

<body>
    <div id="error">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

templates/layouts/horizontal.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - {{ web_title }}</title>
    {% block stylesfirst %}{% endblock %}
    <link rel="stylesheet" href="assets/css/main/app.css">
    <link rel="stylesheet" href="assets/css/main/app-dark.css">
    <link rel="shortcut icon" href="assets/images/logo/favicon.svg" type="image/x-icon">
    <link rel="shortcut icon" href="assets/images/logo/favicon.png" type="image/png">
    {% block styles %}{% endblock %}
</head>

<body>
    <div id="app">
        <div id="main" class="layout-horizontal">
            <header class="mb-5">
                <div class="header-top">
                    <div class="container">
                        <div class="logo">
                            <a href="index.html"><img src="assets/images/logo/logo.svg" alt="Logo"></a>
                        </div>
                        <div class="header-top-right">

                            <div class="dropdown">
                                <a href="#" id="topbarUserDropdown" class="user-dropdown d-flex align-items-center dropend dropdown-toggle " data-bs-toggle="dropdown" aria-expanded="false">
                                    <div class="avatar avatar-md2" >
                                        <img src="assets/images/faces/1.jpg" alt="Avatar">
                                    </div>
                                    <div class="text">
                                        <h6 class="user-dropdown-name">John Ducky</h6>
                                        <p class="user-dropdown-status text-sm text-muted">Member</p>
                                    </div>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end shadow-lg" aria-labelledby="topbarUserDropdown">
                                  <li><a class="dropdown-item" href="#">My Account</a></li>
                                  <li><a class="dropdown-item" href="#">Settings</a></li>
                                  <li><hr class="dropdown-divider"></li>
                                  <li><a class="dropdown-item" href="auth-login.html">Logout</a></li>
                                </ul>
                            </div>

                            <!-- Burger button responsive -->
                            <a href="#" class="burger-btn d-block d-xl-none">
                                <i class="bi bi-justify fs-3"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <nav class="main-navbar">
                    <div class="container">
                        <ul>
                            {% set maxSubmenuItemY = 8 %}
                            {% for menuItem in horizontalMenuItems %}
                            {% if not menuItem.isTitle %}
                            <li
                                class="menu-item {{ 'active' if (menuItem.url == filename or filename|startsWith(menuItem.key)) }} {{'has-sub' if menuItem.submenu.length > 0 }}">
                                <a href="{{menuItem.url if menuItem.url!==undefined else '#'}}" class='menu-link'>
                                    <span><i class="bi bi-{{ menuItem.icon }}"></i> {{menuItem.name}}</span>
                                </a>{% if menuItem.submenu.length > 0 %}
                                <div
                                    class="submenu {{ 'active' if (sub.url and sub.url == filename or filename|startsWith(sidebarItem.key)) }}">
                                    <!-- Wrap to submenu-group-wrapper if you want 3-level submenu. Otherwise remove it. -->
                                    <div class="submenu-group-wrapper">
                                        {% for sub in menuItem.submenu %}
                                        {% if loop.index % maxSubmenuItemY == 1 %}
                                        <ul class="submenu-group">
                                            {% endif %}
                                            <li
                                                class="submenu-item {{ 'active' if sub.url == filename }} {{'has-sub' if sub.submenu.length > 0 }}">
                                                <a href="{{sub.url if sub.url!==undefined else '#'}}"
                                                    class='submenu-link'>{{ sub.name }}</a>

                                                {% if sub.submenu.length > 0 %}
                                                <!-- 3 Level Submenu -->
                                                <ul class="subsubmenu">
                                                    {% for subsub in sub.submenu %}
                                                    <li class="subsubmenu-item ">
                                                        <a href="{{ subsub.url }}" class="subsubmenu-link">{{
                                                            subsub.name }}</a>
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                                {% endif %}
                                            </li>
                                            {% if (loop.index % maxSubmenuItemY == 0) or (loop.last) %}
                                        </ul>
                                        {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>{% endif %}
                            </li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </nav>

            </header>

            <div class="content-wrapper container">
                {% block content %}{% endblock %}
            </div>

            <footer>
                <div class="container">
                    <div class="footer clearfix mb-0 text-muted">
                        <div class="float-start">
                            <p>2021 &copy; Mazer</p>
                        </div>
                        <div class="float-end">
                            <p>Crafted with <span class="text-danger"><i class="bi bi-heart"></i></span> by <a
                                href="https://saugi.me">Saugi</a></p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="assets/js/bootstrap.js"></script>
    <script src="assets/js/app.js"></script>
    <script src="assets/js/pages/horizontal-layout.js"></script>
    {% block js %}{% endblock %}
</body>

</html>

templates/layouts/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - {{ web_title }}</title>
    {% block stylesfirst %}{% endblock %}
    <link rel="stylesheet" href="{% static 'assets/css/main/app.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/main/app-dark.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/shared/iconly.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/logo/favicon.svg' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'assets/images/logo/favicon.png' %}" type="image/png">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% block styles %}{% endblock %}
</head>

<body>
    <script src="{% static 'assets/js/initTheme.js' %}"></script>
    <div id="app">
        <div id="sidebar" class="active">
            {% include "layouts/sidebar.html" %}
        </div>
        <div id="main">
            <header class="mb-3">
                <a href="#" class="burger-btn d-block d-xl-none">
                    <i class="bi bi-justify fs-3"></i>
                </a>
            </header>
            {% block content %}{% endblock %}
            <footer>
             <div class="footer clearfix mb-0 text-muted">
                    <div class="float-start">
                       <!-- <p>2021 &copy; Mazer</p> -->
                    </div>
                    <div class="float-end">
                        {% comment %} <p>Crafted with <span class="text-danger"><i class="bi bi-heart"></i></span> by <a
                                href="https://saugi.me">Saugi</a></p> {% endcomment %}
                    </div>
                </div> 
            </footer>
        </div>
    </div>
    <script src="{% static 'assets/js/bootstrap.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>
    {% block js %}{% endblock %}
</body>

</html>

templates/layouts/rtl.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - {{ web_title }}</title>
    {% block stylesfirst %}{% endblock %}
    <link rel="stylesheet" href="assets/css/app.rtl.css">
    <link rel="stylesheet" href="assets/css/main/app-dark.css">
    <link rel="shortcut icon" href="assets/images/logo/favicon.svg" type="image/x-icon">
    <link rel="shortcut icon" href="assets/images/logo/favicon.png" type="image/png">
    {% block styles %}{% endblock %}
</head>

<body>
    <div id="app">
        <div id="sidebar" class="active">
            {% include "layouts/sidebar.html" %}
        </div>
        <div id="main">
            <header class="mb-3">
                <a href="#" class="burger-btn d-block d-xl-none">
                    <i class="bi bi-justify fs-3"></i>
                </a>
            </header>
            {% block content %}{% endblock %}
            <footer>
                <div class="footer clearfix mb-0 text-muted">
                    <div class="float-start">
                        <p>2021 &copy; Mazer</p>
                    </div>
                    <div class="float-end">
                        <p>Crafted with <span class="text-danger"><i class="bi bi-heart"></i></span> by <a
                            href="https://saugi.me">Saugi</a></p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="assets/js/bootstrap.js"></script>
    <script src="assets/js/app.js"></script>
    {% block js %}{% endblock %}
</body>

</html>

templates/layouts/sidebar.html
{% load static i18n %}
<div class="sidebar-wrapper active">
    <div class="sidebar-header position-relative">
        <div class="d-flex justify-content-between align-items-center">
            <div class="logo">
                <a href="{% url 'home' %}"><img src="{% static 'assets/images/logo/logo.svg' %}" alt="Logo" srcset=""></a>
            </div>
            <div class="theme-toggle d-flex gap-2  align-items-center mt-2">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true"
                    role="img" class="iconify iconify--system-uicons" width="20" height="20"
                    preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21">
                    <g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round"
                        stroke-linejoin="round">
                        <path
                            d="M10.5 14.5c2.219 0 4-1.763 4-3.982a4.003 4.003 0 0 0-4-4.018c-2.219 0-4 1.781-4 4c0 2.219 1.781 4 4 4zM4.136 4.136L5.55 5.55m9.9 9.9l1.414 1.414M1.5 10.5h2m14 0h2M4.135 16.863L5.55 15.45m9.899-9.9l1.414-1.415M10.5 19.5v-2m0-14v-2"
                            opacity=".3"></path>
                        <g transform="translate(-210 -1)">
                            <path d="M220.5 2.5v2m6.5.5l-1.5 1.5"></path>
                            <circle cx="220.5" cy="11.5" r="4"></circle>
                            <path d="m214 5l1.5 1.5m5 14v-2m6.5-.5l-1.5-1.5M214 18l1.5-1.5m-4-5h2m14 0h2"></path>
                        </g>
                    </g>
                </svg>
                <div class="form-check form-switch fs-6">
                    <input class="form-check-input  me-0" type="checkbox" id="toggle-dark" style="cursor: pointer">
                    <label class="form-check-label"></label>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true"
                    role="img" class="iconify iconify--mdi" width="20" height="20" preserveAspectRatio="xMidYMid meet"
                    viewBox="0 0 24 24">
                    <path fill="currentColor"
                        d="m17.75 4.09l-2.53 1.94l.91 3.06l-2.63-1.81l-2.63 1.81l.91-3.06l-2.53-1.94L12.44 4l1.06-3l1.06 3l3.19.09m3.5 6.91l-1.64 1.25l.59 1.98l-1.7-1.17l-1.7 1.17l.59-1.98L15.75 11l2.06-.05L18.5 9l.69 1.95l2.06.05m-2.28 4.95c.83-.08 1.72 1.1 1.19 1.85c-.32.45-.66.87-1.08 1.27C15.17 23 8.84 23 4.94 19.07c-3.91-3.9-3.91-10.24 0-14.14c.4-.4.82-.76 1.27-1.08c.75-.53 1.93.36 1.85 1.19c-.27 2.86.69 5.83 2.89 8.02a9.96 9.96 0 0 0 8.02 2.89m-1.64 2.02a12.08 12.08 0 0 1-7.8-3.47c-2.17-2.19-3.33-5-3.49-7.82c-2.81 3.14-2.7 7.96.31 10.98c3.02 3.01 7.84 3.12 10.98.31Z">
                    </path>
                </svg>
            </div>
            <div class="sidebar-toggler  x">
                <a href="{% url 'home' %}" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
            </div>
        </div>
    </div>
     <div class="sidebar-menu">
        <ul class="menu">
            <li class="sidebar-title">{% trans 'Menu' %}</li>
            <li class="sidebar-item">
                <a href="{% url 'home' %}" class='sidebar-link'>
                    <i class="bi bi-grid-fill"></i>
                    <span>{% trans 'Dashboard' %}</span>
                </a>
                <ul class="submenu">
                    <li class="submenu-item ">
                        <a href=""></a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-item">
                <a href="{% url 'category_list' %}" class="sidebar-link">
                    <i class="bi bi-stack"></i>
                    <span>{% trans 'Category' %}</span>
                </a>
            </li>
            <li class="sidebar-item">
                <a href="{% url 'product_price_list' %}" class="sidebar-link">
                    <i class="bi bi-grid-1x2-fill"></i>
                    <span>{% trans 'Prices' %}</span>
                </a>
                <ul class="submenu">
                    <li class="submenu-item">
                        <a href="">Selling</a>
                    </li>
                </ul>
                <ul class="submenu">
                    <li class="submenu-item">
                        <a href="">Byuing</a>
                    </li>
                </ul>
                <ul class="submenu">
                    <li class="submenu-item">
                        <a href="">Shipping</a>
                    </li>
                </ul>
            </li>
            <div class="py-sm-4 mt-sm-auto ms-auto ms-sm-0 flex-shrink-1">
                <li class="sidebar-title">{% trans 'Raise Support' %}</li>
                    <li class="sidebar-item">
                        <a href="{% url 'ticket_list' %}" class="sidebar-link">
                            <i class="bi bi-life-preserver"></i>
                            <span>{% trans 'Ticket' %}</span>
                        </a>
                    </li>
                </li>
            </div>
        </ul>
    </div> 
</div>

templates/layouts/vertical-1-column.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Layout Vertical 1 Column - Mazer</title>
    <link rel="stylesheet" href="assets/css/main/app.css">
    <link rel="stylesheet" href="assets/css/main/app-dark.css">
    <link rel="shortcut icon" href="assets/images/logo/favicon.svg" type="image/x-icon">
    <link rel="shortcut icon" href="assets/images/logo/favicon.png" type="image/png">
</head>

<body>
    <nav class="navbar navbar-light">
        <div class="container d-block">
            <a href="index.html"><i class="bi bi-chevron-left"></i></a>
            <a class="navbar-brand ms-4" href="index.html">
                <img src="assets/images/logo/logo.svg">
            </a>
        </div>
    </nav>
    {% block content %}{% endblock %}
    <script src="assets/js/app.js"></script>
</body>

</html>

templates/layouts/vertical-navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - {{ web_title }}</title>
    {% block stylesfirst %}{% endblock %}
    <link rel="stylesheet" href="assets/css/main/app.css">
    <link rel="stylesheet" href="assets/css/main/app-dark.css">
    {% block styles %}{% endblock %}
    <link rel="shortcut icon" href="assets/images/logo/favicon.svg" type="image/x-icon">
    <link rel="shortcut icon" href="assets/images/logo/favicon.png" type="image/png">
</head>

<body>
    <div id="app">
        <div id="sidebar" class="active">
            {% include "layouts/sidebar.html" %}
        </div>
        <div id="main" class='layout-navbar navbar-fixed'>
            <header>
                <nav class="navbar navbar-expand navbar-light navbar-top">
                    <div class="container-fluid">
                        <a href="#" class="burger-btn d-block">
                            <i class="bi bi-justify fs-3"></i>
                        </a>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mb-lg-0">
                                <li class="nav-item dropdown me-1">
                                    <a class="nav-link active dropdown-toggle text-gray-600" href="#" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        <i class='bi bi-envelope bi-sub fs-4'></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                                        <li>
                                            <h6 class="dropdown-header">Mail</h6>
                                        </li>
                                        <li><a class="dropdown-item" href="#">No new mail</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown me-3">
                                    <a class="nav-link active dropdown-toggle text-gray-600" href="#" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                                        <i class='bi bi-bell bi-sub fs-4'></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-end notification-dropdown" aria-labelledby="dropdownMenuButton">
                                        <li class="dropdown-header">
                                            <h6>Notifications</h6>
                                        </li>
                                        <li class="dropdown-item notification-item">
                                            <a class="d-flex align-items-center" href="#">
                                                <div class="notification-icon bg-primary">
                                                    <i class="bi bi-cart-check"></i>
                                                </div>
                                                <div class="notification-text ms-4">
                                                    <p class="notification-title font-bold">Successfully check out</p>
                                                    <p class="notification-subtitle font-thin text-sm">Order ID #256</p>
                                                </div>
                                            </a>
                                        </li>
                                        <li class="dropdown-item notification-item">
                                            <a class="d-flex align-items-center" href="#">
                                                <div class="notification-icon bg-success">
                                                    <i class="bi bi-file-earmark-check"></i>
                                                </div>
                                                <div class="notification-text ms-4">
                                                    <p class="notification-title font-bold">Homework submitted</p>
                                                    <p class="notification-subtitle font-thin text-sm">Algebra math homework</p>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <p class="text-center py-2 mb-0"><a href="#">See all notification</a></p>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <div class="dropdown">
                                <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                    <div class="user-menu d-flex">
                                        <div class="user-name text-end me-3">
                                            <h6 class="mb-0 text-gray-600">John Ducky</h6>
                                            <p class="mb-0 text-sm text-gray-600">Administrator</p>
                                        </div>
                                        <div class="user-img d-flex align-items-center">
                                            <div class="avatar avatar-md">
                                                <img src="assets/images/faces/1.jpg">
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton" style="min-width: 11rem;">
                                    <li>
                                        <h6 class="dropdown-header">Hello, John!</h6>
                                    </li>
                                    <li><a class="dropdown-item" href="#"><i class="icon-mid bi bi-person me-2"></i> My
                                            Profile</a></li>
                                    <li><a class="dropdown-item" href="#"><i class="icon-mid bi bi-gear me-2"></i>
                                            Settings</a></li>
                                    <li><a class="dropdown-item" href="#"><i class="icon-mid bi bi-wallet me-2"></i>
                                            Wallet</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="#"><i
                                                class="icon-mid bi bi-box-arrow-left me-2"></i> Logout</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </nav>
            </header>
            <div id="main-content">
                {% block content %}{% endblock %}
            </div>
            <footer>
                <div class="footer clearfix mb-0 text-muted">
                    <div class="float-start">
                        <p>2021 &copy; Mazer</p>
                    </div>
                    <div class="float-end">
                        <p>Crafted with <span class="text-danger"><i class="bi bi-heart-fill icon-mid"></i></span>
                            by <a href="https://ahmadsaugi.com">Saugi</a></p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="assets/js/bootstrap.js"></script>
    <script src="assets/js/app.js"></script>
    {% block js %}{% endblock %}
</body>

</html>